defmodule RiskInit do
  @moduledoc """
  RiskInit keeps the contexts that define your domain
  and business logic.

  Contexts are also responsible for managing your data, regardless
  if it comes from the database, an external API or others.
  """

  import Ecto.Query, only: [from: 2]

  alias Risk4.Repo
  alias Risk4.Shared
  alias Risk4.Assessment
  alias Risk4.Accounts
  alias Risk4.Accounts.Login
  alias Risk4.Asset


  def run_users do
    Repo.delete_all(Shared.User)
    active_stat_query = from s in "statuses",
      where: s.name == "Active",
      select: s.id
    stat = Repo.one(active_stat_query)
    Shared.create_user(%{fname: "Test", lname: "User", email: "jaronp@gmail.com",
                         avatar: "test.jpg", status_id: stat, phone: "0403434638",
                        level: 1})
  end


  def run do
    Repo.delete_all(Shared.Status)
    Shared.create_status(%{name: "Active", description: "Active Status indicates the record is in use and progressing"})
    Shared.create_status(%{name: "Inactive", description: "Inactive Status indicates the record is open but not progressing"})
    Shared.create_status(%{name: "Overdue", description: "Overdue Status indicates the record is open and past it's due date"})
    Shared.create_status(%{name: "Closed", description: "Closed Status indicates the record is no longer being worked on"})
    Shared.create_status(%{name: "Complete", description: "Complete Status indicates the record is finalised and no longer being worked on"})
    Shared.create_status(%{name: "Cancelled", description: "Cancelled Status indicates the record is not active and not used within the system"})
    Shared.create_status(%{name: "New", description: "New Status indicates the record has been created but is not in use"})
  end

  def run_threat do
    Repo.delete_all(Assessment.Threat)
    active_stat_query = from s in "statuses",
      where: s.name == "Active",
      select: s.id
    stat = Repo.one(active_stat_query)

    Assessment.create_threat(%{name: "Breach of contractual relations", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Breach of legislation", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Damage caused by a third party", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Damages resulting from penetration testing", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Destruction of records", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Eavesdropping", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Embezzlement", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Employees going on strike", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Equipment malfunction", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Failure of communication links", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Falsification of records", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Fraud from a cyber criminal", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Fraud from an internal party", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Improper disclosure of passwords", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Improper disclosure of sensitive information", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Industrial espionage", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Interruption of business processes", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Lack of data integrity", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Loss of support services", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Maintenance errors", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Malicious code", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Misuse of information systems", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Natural or man-made disaster", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Phishing scams", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Power failure", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Sensitive data being compromised", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Social engineering", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Terrorism threat in the immediate vicinity or affecting nearby transport and logistics", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Theft of equipment", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Theft of sensitive data", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Unauthorised access to the information system", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Unauthorised access to the network", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Unauthorised changes of records", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Unauthorised physical access", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Unauthorised use of copyright material", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Access to the network by unauthorized persons", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Bomb attack", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Bomb threat", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Compromising confidential information", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Concealing user identity", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Disaster (human caused)", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Disaster (natural)", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Disclosure of information", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Disclosure of passwords", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Errors in maintenance", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Fire", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Flood", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Fraud", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Information leakage", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Loss of electricity", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Malfunction of equipment", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Misuse of audit tools", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Pollution", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Software errors", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Strike", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Terrorist attacks", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Theft", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Thunderstroke", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Unintentional change of data in an information system", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Unauthorized access to the information system", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Unauthorized changes of records", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Unauthorized installation of software", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Unauthorized physical access", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Unauthorized use of copyright material", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Unauthorized use of software", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "User error", description: "TBC", status_id: stat})
    Assessment.create_threat(%{name: "Vandalism", description: "TBC", status_id: stat})
  end


  def run_vulnerability do
    Repo.delete_all(Assessment.Vulnerability)
    active_stat_query = from s in "statuses",
      where: s.name == "Active",
      select: s.id
    stat = Repo.one(active_stat_query)
    Assessment.create_vulnerability(%{name: "Employees not receiving adequate training", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Equipment not being replaced when it is no longer fit for purpose", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Hard drives being disposed of without sensitive data having been deleted", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Improper cabling security and management", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Improper change management", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Improper internal audit", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Improper network management", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Improper validation of the processed data", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Inadequate or irregular system backups", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Inadequate physical security controls", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Insufficient processes or technologies to prevent malicious files from being downloaded", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Insufficient processes or technologies to prevent sensitive data from being copied", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Insufficient software testing", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Insufficient processes or technologies to prevent users from downloading unapproved software", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Inadequate protection of cryptographic keys", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Lack of systems for identification and authentication", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "No procedure for removing access rights upon termination of employment", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "No protection for mobile equipment", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Operational and testing facilities not being properly segregated", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Passwords not being changed from default settings", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Passwords not being strong enough", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Poor or non-existent access control policy", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Poor or non-existent clean desk and clear screen policy", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Poor or non-existent of internal documentation", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Poor staff morale and potential for malicious action", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Premises is vulnerable to flooding, fire or other disruptive event", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Sensitive data not being properly classified", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Staff duties not being properly segregated", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Staff not receiving security awareness training", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "User rights are not reviewed regularly", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Unprotected public networks", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Water or heat damage to equipment", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Complicated user interface", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Default passwords not changed", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Disposal of storage media without deleting data", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Equipment sensitivity to changes in voltage", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Equipment sensitivity to moisture and contaminants", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Equipment sensitivity to temperature", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Inadequate cabling security", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Inadequate capacity management", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Inadequate change management", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Inadequate classification of information", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Inadequate control of physical access", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Inadequate maintenance", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Inadequate network management", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Inadequate or irregular backup", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Inadequate password management", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Inadequate physical protection", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Inadequate replacement of older equipment", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Inadequate security awareness", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Inadequate segregation of duties", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Inadequate segregation of operational and testing facilities", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Inadequate supervision of employees", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Inadequate supervision of vendors", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Inadequate training of employees", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Incomplete specification for software development", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Lack of access control policy", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Lack of clean desk and clear screen policy", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Lack of control over the input and output data", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Lack of internal documentation", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Lack of or poor implementation of internal audit", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Lack of policy for the use of cryptography", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Lack of procedure for removing access rights upon termination of employment", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Lack of protection for mobile equipment", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Lack of redundancy", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Lack of validation of the processed data", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Location vulnerable to flooding", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Poor selection of test data", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Single copy", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Too much power in one person", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Uncontrolled copying of data", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Uncontrolled download from the Internet", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Uncontrolled use of information systems", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Undocumented software", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Unmotivated employees", description: "TBC", status_id: stat})
    Assessment.create_vulnerability(%{name: "Unprotected public network connections", description: "TBC", status_id: stat})

  end

  def run_login do
    Repo.delete_all(Accounts.Login)
    Accounts.register_login(%{email: "xxxxxxxxx@example.com", password: "***********************"})
  end

  def run_controls do

    Repo.delete_all(Assessment.Control)
    active_stat_query = from s in "statuses",
      where: s.name == "Active",
      select: s.id
    stat = Repo.one(active_stat_query)
    Assessment.create_control(%{name: "Policy And Procedures", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Account Management", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Access Enforcement", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Information Flow Enforcement", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Separation Of Duties", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Least Privilege", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Unsuccessful Logon Attempts", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "System Use Notification", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Previous Logon Notification", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Concurrent Session Control", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Device Lock", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Session Termination", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Supervision And Review - Access Control", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Permitted Actions Without Identification Or Authentication", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Automated Marking", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Security And Privacy Attributes", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Remote Access", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Wireless Access", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Access Control For Mobile Devices", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Use Of External Systems", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Information Sharing", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Publicly Accessible Content", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Data Mining Protection", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Access Control Decisions", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Reference Monitor", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Policy And Procedures", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Literacy Training And Awareness", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Role-Based Training", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Training Records", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Contacts With Security Groups And Associations", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Training Feedback", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Policy And Procedures", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Event Logging", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Content Of Audit Records", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Audit Log Storage Capacity", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Response To Audit Logging Process Failures", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Audit Record Review, Analysis, And Reporting", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Audit Record Reduction And Report Generation", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Time Stamps", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Protection Of Audit Information", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Non-Repudiation", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Audit Record Retention", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Audit Record Generation", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Monitoring For Information Disclosure", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Session Audit", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Alternate Audit Logging Capability", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Cross-Organizational Audit Logging", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Policy And Procedures", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Control Assessments", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Information Exchange", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Security Certification", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Plan Of Action And Milestones", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Authorization", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Continuous Monitoring", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Penetration Testing", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Internal System Connections", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Policy And Procedures", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Baseline Configuration", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Configuration Change Control", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Impact Analyses", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Access Restrictions For Change", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Configuration Settings", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Least Functionality", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "System Component Inventory", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Configuration Management Plan", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Software Usage Restrictions", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "User-Installed Software", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Information Location", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Data Action Mapping", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Signed Components", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Policy And Procedures", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Contingency Plan", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Contingency Training", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Contingency Plan Testing", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Contingency Plan Update", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Alternate Storage Site", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Alternate Processing Site", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Telecommunications Services", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "System Backup", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "System Recovery And Reconstitution", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Alternate Communications Protocols", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Safe Mode", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Alternative Security Mechanisms", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Policy And Procedures", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Identification And Authentication (Organizational Users)", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Device Identification And Authentication", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Identifier Management", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Authenticator Management", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Authentication Feedback", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Cryptographic Module Authentication", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Identification And Authentication (Non-Organizational Users)", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Service Identification And Authentication", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Adaptive Authentication", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Re-Authentication", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Identity Proofing", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Policy And Procedures", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Incident Response Training", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Incident Response Testing", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Incident Handling", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Incident Monitoring", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Incident Reporting", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Incident Response Assistance", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Incident Response Plan", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Information Spillage Response", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Integrated Information Security Analysis Team", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Policy And Procedures", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Controlled Maintenance", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Maintenance Tools", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Nonlocal Maintenance", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Maintenance Personnel", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Timely Maintenance", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Field Maintenance", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Policy And Procedures", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Media Access", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Media Marking", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Media Storage", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Media Transport", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Media Sanitization", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Media Use", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Media Downgrading", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Policy And Procedures", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Physical Access Authorizations", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Physical Access Control", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Access Control For Transmission", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Access Control For Output Devices", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Monitoring Physical Access", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Visitor Control", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Visitor Access Records", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Power Equipment And Cabling", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Emergency Shutoff", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Emergency Power", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Emergency Lighting", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Fire Protection", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Environmental Controls", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Water Damage Protection", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Delivery And Removal", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Alternate Work Site", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Location Of System Components", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Information Leakage", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Asset Monitoring And Tracking", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Electromagnetic Pulse Protection", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Component Marking", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Facility Location", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Policy And Procedures", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "System Security And Privacy Plans", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "System Security Plan Update", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Rules Of Behavior", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Privacy Impact Assessment", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Security-Related Activity Planning", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Concept Of Operations", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Security And Privacy Architectures", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Central Management", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Baseline Selection", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Baseline Tailoring", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Information Security Program Plan", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Information Security Program Leadership Role", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Information Security And Privacy Resources", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Plan Of Action And Milestones Process", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "System Inventory", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Measures Of Performance", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Enterprise Architecture", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Critical Infrastructure Plan", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Risk Management Strategy", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Authorization Process", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Mission And Business Process Definition", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Insider Threat Program", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Security And Privacy Workforce", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Testing, Training, And Monitoring", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Security And Privacy Groups And Associations", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Threat Awareness Program", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Protecting Controlled Unclassified Information On External Systems", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Privacy Program Plan", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Privacy Program Leadership Role", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Dissemination Of Privacy Program Information", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Accounting Of Disclosures", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Personally Identifiable Information Quality Management", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Data Governance Body", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Data Integrity Board", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Minimization Of Personally Identifiable Information Used In Testing, Training, And Research", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Complaint Management", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Privacy Reporting", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Risk Framing", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Risk Management Program Leadership Roles", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Supply Chain Risk Management Strategy", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Continuous Monitoring Strategy", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Purposing", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Policy And Procedures", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Position Risk Designation", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Personnel Screening", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Personnel Termination", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Personnel Transfer", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Access Agreements", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "External Personnel Security", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Personnel Sanctions", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Position Descriptions", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Policy And Procedures", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Authority To Process Personally Identifiable Information", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Personally Identifiable Information Processing Purposes", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Consent", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Privacy Notice", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "System Of Records Notice", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Specific Categories Of Personally Identifiable Information", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Computer Matching Requirements", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Policy And Procedures", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Security Categorization", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Risk Assessment", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Risk Assessment Update", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Vulnerability Monitoring And Scanning", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Technical Surveillance Countermeasures Survey", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Risk Response", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Privacy Impact Assessments", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Criticality Analysis", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Threat Hunting", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Policy And Procedures", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Allocation Of Resources", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "System Development Life Cycle", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Acquisition Process", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "System Documentation", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Software Usage Restrictions", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "User-Installed Software", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Security And Privacy Engineering Principles", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "External System Services", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Developer Configuration Management", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Developer Testing And Evaluation", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Supply Chain Protection", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Trustworthiness", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Criticality Analysis", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Development Process, Standards, And Tools", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Developer-Provided Training", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Developer Security And Privacy Architecture And Design", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Tamper Resistance And Detection", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Component Authenticity", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Customized Development Of Critical Components", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Developer Screening", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Unsupported System Components", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Specialization", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Policy And Procedures", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Separation Of System And User Functionality", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Security Function Isolation", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Information In Shared System Resources", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Denial-Of-Service Protection", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Resource Availability", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Boundary Protection", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Transmission Confidentiality And Integrity", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Transmission Confidentiality", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Network Disconnect", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Trusted Path", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Cryptographic Key Establishment And Management", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Cryptographic Protection", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Public Access Protections", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Collaborative Computing Devices And Applications", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Transmission Of Security And Privacy Attributes", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Public Key Infrastructure Certificates", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Mobile Code", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Voice Over Internet Protocol", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Thin Nodes", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Decoys", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Platform-Independent Applications", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Protection Of Information At Rest", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Heterogeneity", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Concealment And Misdirection", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Covert Channel Analysis", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "System Partitioning", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Transmission Preparation Integrity", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Non-Modifiable Executable Programs", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "External Malicious Code Identification", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Distributed Processing And Storage", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Out-Of-Band Channels", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Operations Security", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Process Isolation", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Wireless Link Protection", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Port And I/O Device Access", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Sensor Capability And Data", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Usage Restrictions", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Detonation Chambers", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "System Time Synchronization", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Cross Domain Policy Enforcement", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Alternate Communications Paths", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Sensor Relocation", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Hardware-Enforced Separation And Policy Enforcement", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Software-Enforced Separation And Policy Enforcement", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Hardware-Based Protection", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Policy And Procedures", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Flaw Remediation", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Malicious Code Protection", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "System Monitoring", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Security Alerts, Advisories, And Directives", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Security And Privacy Function Verification", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Software, Firmware, And Information Integrity", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Spam Protection", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Information Input Restrictions", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Information Input Validation", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Error Handling", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Information Management And Retention", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Predictable Failure Prevention", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Non-Persistence", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Information Output Filtering", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Memory Protection", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Fail-Safe Procedures", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Personally Identifiable Information Quality Operations", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "De-Identification", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Tainting", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Information Refresh", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Information Diversity", description: "TBC", status_id: stat})
    Assessment.create_control(%{name: "Information Fragmentation", description: "TBC", status_id: stat})




  end



  def run_assets do


    Repo.delete_all(Assessment.Vulnerability)
    active_stat_query = from s in "statuses",
      where: s.name == "Active",
      select: s.id
    stat = Repo.one(active_stat_query)

    Asset.create_item(%{name: "Computers", availablity: 3, confidentiality: 3, integrity: 2, justification: "TBC", value: 5, status_id: stat})
    Asset.create_item(%{name: "Servers", availablity: 3, confidentiality: 3, integrity: 2, justification: "TBC", value: 5, status_id: stat})
    Asset.create_item(%{name: "Switches/routers/hubs", availablity: 3, confidentiality: 3, integrity: 3, justification: "TBC", value: 4, status_id: stat})
    Asset.create_item(%{name: "Access points", availablity: 3, confidentiality: 3, integrity: 3, justification: "TBC", value: 4, status_id: stat})
    Asset.create_item(%{name: "Access card readers", availablity: 3, confidentiality: 3, integrity: 3, justification: "TBC", value: 4, status_id: stat})
    Asset.create_item(%{name: "Firewalls", availablity: 3, confidentiality: 3, integrity: 3, justification: "TBC", value: 4, status_id: stat})
    Asset.create_item(%{name: "Communication equipment", availablity: 3, confidentiality: 3, integrity: 3, justification: "TBC", value: 4, status_id: stat})
    Asset.create_item(%{name: "Data storage", availablity: 3, confidentiality: 3, integrity: 3, justification: "TBC", value: 4, status_id: stat})
    Asset.create_item(%{name: "Cabinets", availablity: 3, confidentiality: 3, integrity: 3, justification: "TBC", value: 4, status_id: stat})
    Asset.create_item(%{name: "Safes", availablity: 3, confidentiality: 3, integrity: 3, justification: "TBC", value: 4, status_id: stat})
    Asset.create_item(%{name: "Server racks", availablity: 3, confidentiality: 3, integrity: 3, justification: "TBC", value: 4, status_id: stat})
    Asset.create_item(%{name: "Outsourced operations", availablity: 3, confidentiality: 3, integrity: 3, justification: "TBC", value: 4, status_id: stat})
    Asset.create_item(%{name: "Outsourced services", availablity: 3, confidentiality: 3, integrity: 3, justification: "TBC", value: 4, status_id: stat})
    Asset.create_item(%{name: "Outsourced telephone operations", availablity: 3, confidentiality: 3, integrity: 3, justification: "TBC", value: 4, status_id: stat})
    Asset.create_item(%{name: "Security services", availablity: 3, confidentiality: 3, integrity: 3, justification: "TBC", value: 4, status_id: stat})
    Asset.create_item(%{name: "IT services", availablity: 3, confidentiality: 3, integrity: 3, justification: "TBC", value: 4, status_id: stat})
    Asset.create_item(%{name: "Databases and data files/soft copies", availablity: 3, confidentiality: 3, integrity: 3, justification: "TBC", value: 4, status_id: stat})
    Asset.create_item(%{name: "System documentation/manual", availablity: 3, confidentiality: 3, integrity: 3, justification: "TBC", value: 4, status_id: stat})
    Asset.create_item(%{name: "User manuals", availablity: 3, confidentiality: 3, integrity: 3, justification: "TBC", value: 4, status_id: stat})
    Asset.create_item(%{name: "Training materials", availablity: 3, confidentiality: 3, integrity: 3, justification: "TBC", value: 4, status_id: stat})
    Asset.create_item(%{name: "Operational or support procedures", availablity: 3, confidentiality: 3, integrity: 3, justification: "TBC", value: 4, status_id: stat})
    Asset.create_item(%{name: "Backup", availablity: 3, confidentiality: 3, integrity: 3, justification: "TBC", value: 4, status_id: stat})
    Asset.create_item(%{name: "AMC document", availablity: 3, confidentiality: 3, integrity: 3, justification: "TBC", value: 4, status_id: stat})
    Asset.create_item(%{name: "Anti-virus software", availablity: 3, confidentiality: 3, integrity: 3, justification: "TBC", value: 4, status_id: stat})
    Asset.create_item(%{name: "Business applications", availablity: 3, confidentiality: 3, integrity: 3, justification: "TBC", value: 4, status_id: stat})
    Asset.create_item(%{name: "Network management system software", availablity: 3, confidentiality: 3, integrity: 3, justification: "TBC", value: 4, status_id: stat})
    Asset.create_item(%{name: "Development tools", availablity: 3, confidentiality: 3, integrity: 3, justification: "TBC", value: 4, status_id: stat})
    Asset.create_item(%{name: "Operating Systems", availablity: 3, confidentiality: 3, integrity: 3, justification: "TBC", value: 4, status_id: stat})
    Asset.create_item(%{name: "Utilities", availablity: 3, confidentiality: 3, integrity: 3, justification: "TBC", value: 4, status_id: stat})
    Asset.create_item(%{name: "Employees", availablity: 3, confidentiality: 3, integrity: 3, justification: "TBC", value: 4, status_id: stat})
    Asset.create_item(%{name: "Customers", availablity: 3, confidentiality: 3, integrity: 3, justification: "TBC", value: 4, status_id: stat})
    Asset.create_item(%{name: "Subscribers", availablity: 3, confidentiality: 3, integrity: 3, justification: "TBC", value: 4, status_id: stat})
    Asset.create_item(%{name: "Contracts", availablity: 3, confidentiality: 3, integrity: 3, justification: "TBC", value: 4, status_id: stat})
    Asset.create_item(%{name: "Contracts", availablity: 3, confidentiality: 3, integrity: 3, justification: "TBC", value: 4, status_id: stat})
    Asset.create_item(%{name: "HR records", availablity: 3, confidentiality: 3, integrity: 3, justification: "TBC", value: 4, status_id: stat})
    Asset.create_item(%{name: "Invoices", availablity: 3, confidentiality: 3, integrity: 3, justification: "TBC", value: 4, status_id: stat})

  end


end
